apiVersion: v1
kind: Pod
metadata:
  name: blocked-pod
spec:
  containers:
    - name: container-1
      image: nginx
    - name: container-2
      image: busybox
    - name: container-3
      image: alpine       