# This policy checks if the annotations on a Pod's metadata satisfy the condition for the container count
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: max-containers-per-pod     
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: max-containers-per-pod
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{request.operation || 'BACKGROUND'}}"
        operator: AnyIn
        value: 
        - CREATE
        - UPDATE
    validate:
      message: "Pods can only have a maximum of 2 containers."
      deny:
        conditions:
          any:
          - key: "{{request.object.spec.containers[] | length(@)}}"
            operator: GreaterThan
            value: "2"